[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
serde = {version = "1.0.195", features = ["derive"]}
tokio = {version = "1.35.1", features = ["rt-multi-thread", "macros"]}
thiserror = "1.0.63"
alloy = { version = "1.0.22", features = ["full"] }
