/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateVoting } from "./PrivateVoting";
export * as factories from "./factories";
export { PrivateVoting__factory } from "./factories/PrivateVoting__factory";
